# Generated by Django 2.2.3 on 2019-07-29 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pgram', '0006_auto_20190729_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='<django.db.models.fields.related.ForeignKey>2019-07-29 17:21:31.639208+00:00',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 17, 24, 6, 452014, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
