# Generated by Django 2.2.3 on 2019-08-01 20:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pgram', '0007_auto_20190729_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 20, 26, 40, 944079, tzinfo=utc), verbose_name='Publish date'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Comment')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 8, 1, 20, 26, 40, 950053, tzinfo=utc), verbose_name='Publish Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pgram.UserModel', verbose_name='Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pgram.PostModel', verbose_name='Post')),
            ],
        ),
    ]
